version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: repairshop
      POSTGRES_PASSWORD: repairshop123
      POSTGRES_DB: repair_shop_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh  # ← Auto-runs on first start
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U repairshop -d repair_shop_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://repairshop:repairshop123@db:5432/repair_shop_db
      ENVIRONMENT: development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app

volumes:
  postgres_data: